# Generated by Django 5.0.6 on 2024-06-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
    ]
