# Generated by Django 5.0.6 on 2024-06-20 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0007_expense_created_at_expense_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
