# Generated by Django 5.0.6 on 2024-06-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0008_alter_expense_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
